---
# file: roles/jenkins/tasks/ansible-install-RedHat.yml

- name: Install RedHat '{{ outer_item.service }}' packages
  package:
    name: "{{ outer_item.packages }}"
    state: latest
  tags:
    - ansible