---
# file: roles/jenkins/defaults/main.yml

# Users
jenkins_vault_user:
  username: 'ansible'
  group: 'ansible'
  file_mode: '0400'
  dir_mode: '0700'

jenkins_admin_user:
  username: 'jenkins'
  group: 'jenkins'
  file_mode: '0700'
  dir_mode: '0700'
  sudo: 'pass'
  gecos: 'Jenkins service'
  shell: '/bin/bash'
  home: 'yes'
  update_pass: 'always'
  role: 'admin'
  
users:
  - "{{ ansible_user_srv }}"
  - "{{ jenkins_admin_user }}"

jenkins_users:
#  - "{{ jenkins_admin_user }}"
  - "{{ developer_user }}"

# Setup
jenkins_home: '/var/lib/jenkins'
jenkins_vault_dir: '/etc/jenkins'
jenkins_vault_passwd_dir: "{{ jenkins_vault_dir }}/.pass"
jenkins_init_admin_password_file: "{{ jenkins_home }}/secrets/initialAdminPassword"
#jenkins_port: 80
jenkins_port: 8080
jenkins_protocol: 'http'
jenkins_external_url: "{{ jenkins_protocol }}://{{ inventory_hostname }}:{{ jenkins_port }}"
# Disable jenkins setup wizard
jenkins_java_options: '-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false'
# Disable CSRF token session improvement (Jenkins 2.176)
jenkins_java_options_extra: ' -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true'
jenkins_debug_level: 5
jenkins_enable_access_log: 'no'
jenkins_handler_max: 100
jenkins_handler_idle: 20
jenkins_sysconfig_file: '/etc/sysconfig/jenkins'
jenkins_sysconfig_temp: 'jenkins-sysconfig'
jenkins_config_file: 'jenkins-config.xml'


# Plugins
jenkins_plugins_state: 'latest'
jenkins_plugin_timeout: 60
jenkins_plugin_updates_expiration: 86400
jenkins_updates_url: 'https://updates.jenkins.io'
jenkins_plugins_with_dependencies: 'yes'

jenkins_plugins:
  mailer:
    enabled: 'yes'
  matrix-auth:
    enabled: 'yes'
  git:
    enabled: 'yes'
  ansible:
    enabled: 'yes'
  github:
    enabled: 'yes'
  # gitlab-plugin:
  #   enabled: 'yes'
  # gitlab-hook:
  #   enabled: 'yes'
#github-branch-source
#github-oauth
#github

# Scripts
jenkins_script_security_init_temp: 'security-init.groovy'
# jenkins_script_security_users_temp: 'security-users.groovy'
jenkins_script_security_users: "{{ lookup('file', 'groovy/security-users.groovy') }}"
jenkins_script_security_strategy_matrix: "{{ lookup('file', 'groovy/security-strategy-matrix.groovy') }}"
jenkins_script_plugin-ansible-setup:  "{{ lookup('file', 'groovy/plugin-ansible-setup.groovy') }}"