---
# file: roles/vagrant/tasks/vagrant-user.yml

# vagrant
- name: Remove vagrant user
  user:
    name: 'vagrant'
    state: 'absent'
    remove: yes

- name: Remove default vagrant sudoers file
  file:
    path: '/etc/sudoers.d/vagrant'
    state: 'absent'

# root
- name: Generate root user password
  shell: "{{ generate_password_command }}"
  register: root_passwd_reg
  no_log: true

- name: Update root user password
  user:
    name: 'root'
    password: "{{ root_passwd_reg.stdout | password_hash('sha512') }}"
    update_password: 'always'
  no_log: true