---
# file: roles/vagrant/tasks/vagrant-user.yml

- name: Generate '{{ item.username }}' user password
  shell: "{{ generate_password_command }}"
  register: user_passwd_reg
  no_log: true

- name: Update '{{ item.username }}' user password
  user:
    name: "{{ item.username }}"
    password: "{{ user_passwd | password_hash('sha512') }}"
    update_password: always
  no_log: true

- name: Generate root user password
  shell: "{{ generate_password_command }}"
  register: root_passwd_reg
  no_log: true

- name: Update root user password
  user:
    name: root
    password: "{{ root_passwd_reg.stdout | password_hash('sha512') }}"
    update_password: always
  no_log: true

- name: Remove default vagrant sudoers file
  file:
    path: /etc/sudoers.d/vagrant
    state: absent