---
# file: roles/jenkins/tasks/jenkins-wait-for-ready.yml

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jenkins_external_url }}/login"
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  retries: 60
  delay: 5
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status['status'] == 200
